modernize (const, let, class, update dep, etc)
jprichardson/node-klaw pull request #43
Opened 2021-08-13 18:21 UTC by jimmywarting

- Updated all dependencies
- Switched to const class, let
- Switched rimraf and mkdirp dep for native version with recursive options

2021-08-17 18:05 UTC, RyanZim commented
This removes graceful-fs, curious what the reasoning was?

2021-08-17 19:22 UTC, jimmywarting commented
Didn't see graceful-fs as needed... fewer dependencies. less to install, faster to start.

2021-09-18 14:09 UTC, RyanZim requested changes
Please remove `package-lock.json` and add it to `.gitignore` or turn it off in `.npmrc`; lockfiles are an anti-pattern for libraries.

2021-09-18 14:09 UTC, RyanZim commented
Sorry for the slow review here; just got out of the hospital. I'm OK with removing graceful-fs.

2021-09-18 14:13 UTC, jimmywarting commented on package.json
> +    "@types/node": "^16.6.1",
removed it, wasn't really needed

2021-09-18 14:15 UTC, jimmywarting commented
> Sorry for the slow review here; just got out of the hospital. I'm OK with removing graceful-fs.

Oh, hope you are better now. I removed the lock file and `@types/node`

2021-09-18 14:21 UTC, RyanZim approved these changes
LGTM; I'm working on getting the broken CI fixed up; will probably need to rebase this once I have that fixed.

2021-09-18 14:35 UTC, RyanZim commented
Landed in 8fbf2d26a2b7f46dce7915052d25947ce6b9a0d2; thanks!

2021-09-18 14:35 UTC, closed without merging